### ISSUE TITLE
Not Receiving Specific Messages in MQTT Subscription

### ISSUE THREAD

**Issue by oddbjorn-larsen** [dji-sdk/Cloud-API-Demo-Web#31]
**Description:**
I am trying to receive values such as `zoom_factor` and `recording_state` for a Matrice 300 RTK with an H20T camera using the latest DJI Cloud API. Despite subscribing to all possible topics, I am not receiving messages related to changes in zoom factor or camera mode.

**Configuration:**

I have configured my `cloud-sdk` to subscribe to all potential topics:
```yaml
cloud-sdk:
  mqtt:
    # Topics that need to be subscribed when initially connecting to mqtt, multiple topics are divided by ",".
    inbound-topic: sys/product/+/status,thing/product/+/requests,thing/product/+/response,thing/product/+/events,thing/product/+/commands,thing/product/+/osd,thing/product/+/state,thing/product/+/services,thing/product/+/services_reply,thing/product/+/events_reply,thing/product/+/requests_reply,thing/product/+/property/set,thing/product/+/property/set_reply,thing/product/+/drc/up,thing/product/+/drc/down
```

**Steps Taken:**
1. Subscribed to the following topics:
    - sys/product/+/status
    - thing/product/+/requests
    - thing/product/+/response
    - thing/product/+/events
    - thing/product/+/commands
    - thing/product/+/osd
    - thing/product/+/state
    - thing/product/+/services
    - thing/product/+/services_reply
    - thing/product/+/events_reply
    - thing/product/+/requests_reply
    - thing/product/+/property/set
    - thing/product/+/property/set_reply
    - thing/product/+/drc/up
    - thing/product/+/drc/down

2. Built a custom frontend and monitored messages in the `cloud_api_sample` container.

3. Ensured the device configuration is supposed to push updates on relevant changes.

**Problem:**
No messages are received when changing the zoom factor or switching the camera mode. I expect to see messages for these events in the subscribed topics but the logs are empty for these specific changes.

**Questions:**
1. **Do I need to set specific properties to `pushMode=1` for these messages to be sent?**
2. **Is there any additional configuration required on the device or in the DJI Cloud API to receive these specific messages?**
3. **Could there be a delay or another reason for these messages not appearing in the MQTT logs?**

**Environment:**
- **Device:** Matrice 300 RTK / H20T
- **API Version:** 1.10.0 DJI Cloud API
- **MQTT Broker:** Configured with EMQX Broker
